apiVersion: batch/v1
kind: CronJob
metadata:
  name: playwright-app-cronjob
spec:
  schedule: "*/30 * * * *" # 30分ごと
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: playwright-app
              image: yryuzu/playwright-app:latest
              resources:
                limits:
                  memory: "512Mi"
                  cpu: "500m"
              envFrom:
                - configMapRef:
                    name: playwright-env-config # ConfigMapから環境変数をロード
              volumeMounts: # Playwright用の共有メモリ
                - name: shm
                  mountPath: /dev/shm
          volumes:
            - name: shm
              emptyDir:
                medium: Memory
          restartPolicy: Never # Jobの失敗時に再起動しない
